import React, { useState } from 'react';
import { LogOut, Database, Code, ChevronDown } from 'lucide-react';

export default function SettingsTab({ onLogout, onShowSetup }) {
  const [sqlOpen, setSqlOpen] = useState(false);

  return (
    <div className="space-y-6">
      
      {/* SQL Script Accordion */}
      <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-4 shadow-lg space-y-3">
        <div 
          onClick={() => setSqlOpen(!sqlOpen)}
          className="flex items-center justify-between cursor-pointer"
        >
          <h4 className="text-xs font-bold text-slate-350 uppercase tracking-wider flex items-center gap-2">
            <Code className="w-4 h-4 text-emerald-400" /> Script SQL Supabase Complet
          </h4>
          <ChevronDown className={`w-4 h-4 text-slate-500 transition-transform duration-300 ${sqlOpen ? 'rotate-180 text-emerald-400' : ''}`} />
        </div>
        
        {sqlOpen && (
          <div className="space-y-3 pt-2">
            <p className="text-xs text-slate-400">Copiez ce script et exécutez-le dans le <strong>SQL Editor</strong> de Supabase pour créer la structure et les politiques de sécurité (RLS) :</p>
            <div className="bg-slate-950 border border-slate-800/80 rounded-xl p-3 text-[9px] font-mono text-slate-350 overflow-x-auto select-all space-y-2 leading-relaxed">
              CREATE TABLE IF NOT EXISTS public.profiles (<br />
              &nbsp;&nbsp;id UUID PRIMARY KEY,<br />
              &nbsp;&nbsp;email TEXT NOT NULL,<br />
              &nbsp;&nbsp;approved BOOLEAN DEFAULT FALSE,<br />
              &nbsp;&nbsp;is_admin BOOLEAN DEFAULT FALSE,<br />
              &nbsp;&nbsp;created_at TIMESTAMPTZ DEFAULT NOW()<br />
              );<br /><br />
              CREATE TABLE IF NOT EXISTS public.dublin_gps (<br />
              &nbsp;&nbsp;id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,<br />
              &nbsp;&nbsp;created_at TIMESTAMPTZ DEFAULT NOW(),<br />
              &nbsp;&nbsp;lat DOUBLE PRECISION NOT NULL,<br />
              &nbsp;&nbsp;lng DOUBLE PRECISION NOT NULL,<br />
              &nbsp;&nbsp;accuracy REAL,<br />
              &nbsp;&nbsp;alt REAL,<br />
              &nbsp;&nbsp;speed REAL,<br />
              &nbsp;&nbsp;user_id UUID REFERENCES auth.users DEFAULT auth.uid()<br />
              );<br /><br />
              CREATE TABLE IF NOT EXISTS public.dublin_photos (<br />
              &nbsp;&nbsp;id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,<br />
              &nbsp;&nbsp;created_at TIMESTAMPTZ DEFAULT NOW(),<br />
              &nbsp;&nbsp;image TEXT NOT NULL,<br />
              &nbsp;&nbsp;user_id UUID REFERENCES auth.users DEFAULT auth.uid()<br />
              );<br /><br />
              CREATE TABLE IF NOT EXISTS public.dublin_journal (<br />
              &nbsp;&nbsp;id UUID PRIMARY KEY DEFAULT gen_random_uuid(),<br />
              &nbsp;&nbsp;created_at TIMESTAMPTZ DEFAULT NOW(),<br />
              &nbsp;&nbsp;content TEXT NOT NULL,<br />
              &nbsp;&nbsp;emoji TEXT NOT NULL,<br />
              &nbsp;&nbsp;user_id UUID DEFAULT auth.uid()<br />
              );<br /><br />
              CREATE TABLE IF NOT EXISTS public.dublin_pints (<br />
              &nbsp;&nbsp;id UUID PRIMARY KEY DEFAULT gen_random_uuid(),<br />
              &nbsp;&nbsp;created_at TIMESTAMPTZ DEFAULT NOW(),<br />
              &nbsp;&nbsp;pub TEXT NOT NULL,<br />
              &nbsp;&nbsp;price NUMERIC(5,2) DEFAULT 0,<br />
              &nbsp;&nbsp;rating INT DEFAULT 5,<br />
              &nbsp;&nbsp;note TEXT,<br />
              &nbsp;&nbsp;user_id UUID DEFAULT auth.uid()<br />
              );<br /><br />
              CREATE TABLE IF NOT EXISTS public.dublin_suggestions (<br />
              &nbsp;&nbsp;id UUID PRIMARY KEY DEFAULT gen_random_uuid(),<br />
              &nbsp;&nbsp;created_at TIMESTAMPTZ DEFAULT NOW(),<br />
              &nbsp;&nbsp;text TEXT NOT NULL,<br />
              &nbsp;&nbsp;submitted_by TEXT NOT NULL,<br />
              &nbsp;&nbsp;completed BOOLEAN DEFAULT FALSE,<br />
              &nbsp;&nbsp;user_id UUID DEFAULT auth.uid()<br />
              );<br /><br />
              ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;<br />
              ALTER TABLE public.dublin_gps ENABLE ROW LEVEL SECURITY;<br />
              ALTER TABLE public.dublin_photos ENABLE ROW LEVEL SECURITY;<br />
              ALTER TABLE public.dublin_journal ENABLE ROW LEVEL SECURITY;<br />
              ALTER TABLE public.dublin_pints ENABLE ROW LEVEL SECURITY;<br />
              ALTER TABLE public.dublin_suggestions ENABLE ROW LEVEL SECURITY;<br /><br />
              -- Politiques RLS (Corrigées sans récursion)<br />
              CREATE POLICY "Tout le monde peut s'inscrire" ON public.profiles FOR INSERT WITH CHECK (true);<br />
              CREATE POLICY "Les membres connectés voient tous les profils" ON public.profiles FOR SELECT USING (auth.role() = 'authenticated');<br />
              CREATE POLICY "Les admins modifient" ON public.profiles FOR UPDATE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les admins suppriment" ON public.profiles FOR DELETE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br /><br />
              CREATE POLICY "Les admins écrivent GPS" ON public.dublin_gps FOR INSERT WITH CHECK ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les membres voient GPS" ON public.dublin_gps FOR SELECT USING ((SELECT approved FROM public.profiles WHERE id = auth.uid()) = true);<br /><br />
              CREATE POLICY "Les admins écrivent Photos" ON public.dublin_photos FOR INSERT WITH CHECK ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les membres voient Photos" ON public.dublin_photos FOR SELECT USING ((SELECT approved FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les admins suppriment Photos" ON public.dublin_photos FOR DELETE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br /><br />
              CREATE POLICY "Les admins écrivent Journal" ON public.dublin_journal FOR INSERT WITH CHECK ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les membres voient Journal" ON public.dublin_journal FOR SELECT USING ((SELECT approved FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les admins suppriment Journal" ON public.dublin_journal FOR DELETE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br /><br />
              CREATE POLICY "Les admins écrivent Pints" ON public.dublin_pints FOR INSERT WITH CHECK ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les membres voient Pints" ON public.dublin_pints FOR SELECT USING ((SELECT approved FROM public.profiles WHERE id = auth.uid()) = true);<br />
              CREATE POLICY "Les admins suppriment Pints" ON public.dublin_pints FOR DELETE USING ((SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = true);<br /><br />
              CREATE POLICY "Membres écrivent Suggestions" ON public.dublin_suggestions FOR INSERT WITH CHECK (auth.role() = 'authenticated');<br />
              CREATE POLICY "Membres voient Suggestions" ON public.dublin_suggestions FOR SELECT USING (auth.role() = 'authenticated');<br />
              CREATE POLICY "Modif Suggestions" ON public.dublin_suggestions FOR UPDATE USING (auth.role() = 'authenticated');<br />
              CREATE POLICY "Suppr Suggestions" ON public.dublin_suggestions FOR DELETE USING (auth.role() = 'authenticated');
            </div>
          </div>
        )}
      </div>

      {/* Local DB / System Actions */}
      <div className="bg-slate-900/40 border border-slate-800 rounded-2xl p-5 shadow-lg backdrop-blur space-y-4">
        <h3 className="text-slate-300 text-sm font-bold flex items-center gap-2">
          <Database className="w-4 h-4 text-emerald-400" /> Session & Configuration
        </h3>
        
        <div className="flex flex-col gap-2">
          <button 
            onClick={onLogout} 
            className="w-full bg-rose-500/10 border border-rose-500/20 hover:bg-rose-500/20 text-rose-400 font-bold py-2.5 px-4 rounded-xl text-xs transition-colors flex items-center justify-center gap-1.5 cursor-pointer"
          >
            <LogOut className="w-4 h-4" /> Se déconnecter
          </button>
          <button 
            onClick={onShowSetup} 
            className="w-full bg-slate-900 border border-slate-850 hover:bg-slate-800 text-slate-350 font-bold py-2.5 px-4 rounded-xl text-xs transition-colors flex items-center justify-center gap-1.5 cursor-pointer"
          >
            <Database className="w-4 h-4" /> Changer de base Supabase
          </button>
        </div>
      </div>

      {/* App Metadata */}
      <div className="text-center text-[10px] text-slate-500 space-y-1">
        <p>Dublin 2026 Dashboard v2.0.0 (React)</p>
        <p>100% Serverless & RLS Protected</p>
      </div>

    </div>
  );
}
